#-------------------------------
# General Site Settings

menu:
#- {name: 'Projects', url: ''}
- {name: 'Blog', url: 'blog/'}
- {name: 'About', url: 'about/'}
- {name: 'CV', url: 'cv/'}
#- {name: 'CVt2', url: 'pages/cv2.html'}
#- {name: 'P1', folder: 'proj-1', file: 'projects/proj-1.html'}
#- {name: 'CV', file: 'projects/cv.md', url: 'cv.html'}
#- {name: 'CV', folder: 'proj-1', file: 'projects/cv.md', url: 'projects/cv.html'}
#- {name: 'Contact', url: 'pages/contact.html'}

#-------------------------------
# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.

seo:
  description: 'Personal website powered by Jekyll and GitHub Pages '
  #rel-author: 'https://plus.google.com/u/0/#'
  #rel-publisher: 'https://plus.google.com/u/0/#'

#-------------------------------
# Google Analytics Section

# Analytics helps you understand who visits your website.
# Learn more at: http://support.google.com/analytics/answer/1008065

# NOTE: If you want to use Google Analytics for basic web tracking: Just uncomment and enter your UA-Code here.

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-analytics-ua: ''

#-------------------------------
# Disqus Section

# Change to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: ''

#-------------------------------
# Work Section

projects:
- {name: 'Blog', folder: 'blog', file: 'blog/'}
- {name: 'About', folder: 'about', file: 'about/'}
- {name: 'CV', folder: 'cv', file: 'cv/'}
- {name: 'Favourites', folder: 'favourites', file: 'favourites/'}
- {name: 'Photo Gallery', folder: 'gallery', file: 'albums/'}
#- {name: 'Gallery', folder: 'gallery', file: 'pages/gallery.html'}
#- {name: 'Project Five', folder: 'proj-5', file: 'projects/proj-5.html'}

#-------------------------------
# Contact Section
#{% assign author_email = {{ site.author_email }} %}
#{% assign author_email = site.author_email %}
#author_email: {{ site.author_email }}

social:
- {icon: 'twitter', link: 'https://twitter.com/SalvadorBuse'}
#- {icon: 'instagram', link: '#'}
- {icon: 'github', link: 'https://github.com/salvadorbuse'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/salvadorbuse/'}
- {icon: 'envelope', link: 'mailto:sbuse@caltech.edu'}
- {icon: <i class="fab fa-orcid"></i>, link: "https://orcid.org/0000-0002-3261-5339"}
#- {icon: 'envelope', link: {{author_email}}}

# social network icons available: 'twitter' / 'facebook' / 'github' / 'pinterest' 'google-plus' / 'linkedin' / 'youtube' / 'instagram' / 'dribbble' / 'behance' / 'soundcloud' / 'vine'

orcid:
- {link: "https://orcid.org/0000-0002-3261-5339"}
